Default:
  epochs: 1000
  cycles: 50
  rollouts: 2
  batches: 40
  evals: 10
  batch_size: 256
  buffer_size: 1000000

  gamma: 0.98
  actor_lr: 0.001
  critic_lr: 0.001
  tau: 0.05  # 1-tau is Polyak factor

  eps: 0.3  # Fraction of completely random actions
  mu: 0.15  # Ornstein-Uhlenbeck mu
  sigma: 0.2  # Ornstein-Uhlenbeck or Gaussian noise sigma
  k: 4  # Ratio of HER experience vs normal experience

  action_clip: 1.
  state_clip: 200.
  goal_clip: 200.
  grad_clip: 5.
  action_norm: 1.  # Action regularization
  actor_net_type: "PosePolicyNet"
  actor_net_nlayers: 4
  actor_net_layer_width: 256
  critic_net_nlayers: 4
  critic_net_layer_width: 256

  early_stop: 0.98
  save: True
  load_pretrained: False
  seed: False  # Integer > 0 or False if no custom seed should be used

# Environment specific configurations. Arguments overwrite the default config.
FlatSHAll-v0:
  epochs: 1000
  kwargs:
      n_eigengrasps: 6

FlatSHCube-v0:
  epochs: 1000
  load_pretrained: True
  kwargs:
    n_eigengrasps: 6

FlatSHCylinder-v0:
  epochs: 1000
  kwargs:
    n_eigengrasps: 6

FlatSHSphere-v0:
  epochs: 1000
  kwargs:
    n_eigengrasps: 6

FlatSHMesh-v0:
  epochs: 1000
  kwargs:
    n_eigengrasps: 6

ObstacleSHCube-v0:
  epochs: 1000
  kwargs:
    n_eigengrasps: 6

UnevenSHCube-v0:
  epochs: 1000
  kwargs:
    n_eigengrasps: 6

UnevenSHMesh-v0:
  epochs: 1000
  kwargs:
    n_eigengrasps: 6

SeaClear-v0:
  actor_net_type: "DDP"

FlatBarrettReduced-v0:
  actor_net_type: "DDP"

FlatBarrettSphere-v0:
  actor_net_type: "DDP"
  # grip_pos (0:3), grip_rot (3:9), grip_state (9:17), grip_velp (17:20), object_pos (20:23),
  # object_rel_pos (23:26), object_rot (26:32), object_rel_rot (32:38), object_velp (38:41),
  # object_velr (41:44)
  state_norm_idx: [0, 1, 2, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 38, 39, 40, 41, 42, 43]

FlatPJOrient-v0:
  actor_net_type: "PosePolicyNet"
  # goal_pos (0:3), goal_rot (3:9)
  goal_norm_idx: [0, 1, 2]
  # grip_pos (0:3), grip_rot (3:9), grip_state (9:11), grip_velp (11:14), object_pos (14:17),
  # object_rel_pos (17:20), object_rot (20:26), object_rel_rot (26:32), object_velp (32:35),
  # object_velr (35:38)
  state_norm_idx: [0, 1, 2, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 32, 33, 34, 35, 36, 37]
  actor_net_nlayers: 4
  actor_net_layer_width: 256
